ExtDirectBundle_api:
    pattern:  /api.js
    defaults: { _controller: ext_direct.controller:getApi, _format: js }

ExtDirectBundle_route:
    pattern: /route
    # .{_format}
    defaults: { _controller: ext_direct.controller:route, _format: json }


