ExtDirectBundle_api:
    pattern:  /api.js
    defaults: { _controller: ext_direct.controller:getApi }

ExtDirectBundle_route:
    pattern: /route
    defaults: { _controller: ext_direct.controller:route }


